src/main/logging/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Apex Logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/logging/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/logging/objects/Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/logging/objects/Log__c/fields/Log_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Time__c</fullName>
    <label>Log Time</label>
    <type>DateTime</type>
</CustomField>

src/main/logging/objects/Log__c/fields/Log_User__c.field-meta.xml
<CustomField>
    <fullName>Log_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/logging/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/logging/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <label>LogEvent</label>
    <pluralLabel>LogEvents</pluralLabel>
</CustomObject>

src/main/logging/objects/LogEvent__e/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/logging/objects/LogEvent__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/logging/objects/LogEvent__e/fields/Log_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Time__c</fullName>
    <label>Log Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/logging/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/logging/classes/LogEventHandler.cls
public without sharing class LogEventHandler extends BaseProcessor {
    List<LogEvent__e> events {get; set;}

    public LogEventHandler(List<LogEvent__e> events) {
        this.events = events;
    }

    protected override void doExecute() {
        List<Log__c> entries = new List<Log__c> {};
        for (LogEvent__e event : events) {
            Log__c entry = new Log__c(
                Category__c = event.Category__c
                , Log_Level__c = event.Log_Level__c
                , Message__c = event.Message__c
                , Log_User__c = event.CreatedById
                , Log_Time__c = event.Log_Time__c
            );
            entries.add(entry);
        }
        List<Database.SaveResult> results = Database.insert(entries, false);
        for (Database.SaveResult result : results) {
            if (result.isSuccess() == false) {
                System.debug(LoggingLevel.ERROR, JSON.serialize(result));
            }
        }
    }

    public static void runHandler() {
        new LogEventHandler(Trigger.new).execute();
    }
}